'use strict';

// The Lesson artifact — Chervil's portable, interactive learning document.
//
// A Lesson is the keystone primitive for the learning vertical: it is authored
// in the desktop app (generated by Sprig from a topic), rendered as an in-app
// "lesson player", and published to a mobile-friendly, swipeable reader. It
// builds on Chervil's existing primitives — a Lesson is a structured Space of
// composed cards, where interactive cards reuse the applet bridge
// (window.chervil.ask) that composed pages already use.
//
// Design notes live in docs/rfcs/0001-interactive-lessons.md. This module is
// pure data: schema, validation, and normalization of model output. It has no
// I/O and no rendering, so it carries no security surface. In particular it is
// the UNTRUSTED-INPUT boundary: model-supplied identity (ids/slug), timestamps,
// provenance, and media `verified` flags are NOT trusted here — the trusted
// caller stamps those.

const { youtubeId } = require('./youtube');

const SCHEMA_VERSION = 1;

const LEVELS = ['beginner', 'intermediate', 'advanced'];

// A lesson is consumed as a flat stream of CARDS grouped into MODULES. The card
// is the unit you swipe through on mobile, so each kind is self-contained.
const CARD_KINDS = ['concept', 'media', 'applet', 'check', 'flashcard'];

/**
 * @typedef {Object} Lesson
 * @property {number} schemaVersion
 * @property {string} id                 Stable, globally-unique id (supplied by the trusted caller).
 * @property {string} slug               Derived from the title.
 * @property {string} title
 * @property {string} subtitle
 * @property {string} topic              The learner's original ask.
 * @property {'beginner'|'intermediate'|'advanced'} level
 * @property {string} summary            1–2 sentence overview.
 * @property {string[]} objectives       What the learner will be able to do.
 * @property {number} estMinutes
 * @property {string[]} tags
 * @property {Module[]} modules
 * @property {Source[]} sources          Citations from live grounding.
 * @property {{enabled:boolean,lastGrounded:string|null}} living
 * @property {string|null} authorModel   Provenance: provider/model that built it.
 * @property {string|null} createdAt
 * @property {string|null} updatedAt
 *
 * @typedef {Object} Module
 * @property {string} id
 * @property {string} title
 * @property {string} summary
 * @property {Card[]} cards
 *
 * @typedef {Object} Source
 * @property {string} title
 * @property {string} url
 *
 * Card kinds (discriminated by `kind`):
 *   concept   { id, kind, title, html }                         explanatory content (composed HTML; may carry media markers)
 *   media     { id, kind, title, provider:'youtube', videoId, caption, verified }
 *   applet    { id, kind, title, prompt }                       a generative interactive widget; `prompt` tells Sprig what to build (HTML composed at render time)
 *   check     { id, kind, title, question, options[], answerIndex, explanation }
 *   flashcard { id, kind, front, back }
 */

let _seq = 0;
function rid(prefix) {
  // Local fallback id (no crypto). Only used when the trusted caller doesn't
  // supply a lesson id — e.g. ad-hoc/test use. Persisted lessons get a unique id
  // from the caller; child ids are then derived from it, so they don't rely on
  // this counter for cross-session uniqueness.
  _seq += 1;
  return `${prefix}_${_seq.toString(36)}`;
}

function str(v, max = 0) {
  let s = v == null ? '' : String(v);
  if (max > 0 && s.length > max) s = s.slice(0, max);
  return s;
}

function strArr(v, maxItems = 0, maxLen = 0) {
  if (!Array.isArray(v)) return [];
  let a = v.map((x) => str(x, maxLen)).filter(Boolean);
  if (maxItems > 0) a = a.slice(0, maxItems);
  return a;
}

function clampInt(v, lo, hi, dflt) {
  const n = Math.round(Number(v));
  if (!Number.isFinite(n)) return dflt;
  return Math.max(lo, Math.min(hi, n));
}

// Strip executable/dangerous markup from model-authored concept HTML. Concept
// cards are contractually "clean semantic HTML" (no <script>), but a
// prompt-injected source could slip one in — and the exported reader runs
// outside the in-app sandbox (a plain file://). This neutralizes the common
// vectors at the untrusted-input boundary so every consumer is covered; the
// exported reader also ships a hardening CSP (lib/lessonHtml.js) as defense in depth.
function sanitizeHtml(s) {
  return String(s == null ? '' : s)
    .replace(/<\s*(script|style|iframe|object|embed|link|meta|base)\b[\s\S]*?<\s*\/\s*\1\s*>/gi, '')
    .replace(/<\s*(script|style|iframe|object|embed|link|meta|base)\b[^>]*\/?>/gi, '')
    .replace(/\son[a-z]+\s*=\s*"[^"]*"/gi, '')
    .replace(/\son[a-z]+\s*=\s*'[^']*'/gi, '')
    .replace(/\son[a-z]+\s*=\s*[^\s>]+/gi, '')
    .replace(/(href|src|xlink:href)\s*=\s*"\s*(?:javascript|data|vbscript):[^"]*"/gi, '$1="#"')
    .replace(/(href|src|xlink:href)\s*=\s*'\s*(?:javascript|data|vbscript):[^']*'/gi, "$1='#'");
}

function slugify(s) {
  return str(s)
    .toLowerCase()
    .replace(/['"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'lesson';
}

/**
 * Coerce one raw card into a valid Card, or null if unsalvageable.
 * @param {object} raw
 * @param {string} [id] stable id for this card (derived from the lesson; falls back to a local id).
 */
function normalizeCard(raw, id) {
  if (!raw || typeof raw !== 'object') return null;
  const cid = id || rid('c');
  const kind = str(raw.kind).toLowerCase();
  switch (kind) {
    case 'concept': {
      const html = sanitizeHtml(str(raw.html, 20000));
      if (!html) return null;
      return { id: cid, kind, title: str(raw.title, 200), html };
    }
    case 'media': {
      const videoId = youtubeId(raw.videoId || raw.url || raw.id);
      if (!videoId) return null; // a media card with no resolvable video is useless
      return {
        id: cid,
        kind,
        title: str(raw.title, 200),
        provider: 'youtube',
        videoId,
        caption: str(raw.caption, 500),
        // The model's claim is meaningless here — this is the untrusted boundary.
        // Only the trusted oEmbed step (Phase 0.5) may set this true.
        verified: false,
      };
    }
    case 'applet': {
      const prompt = str(raw.prompt, 2000);
      if (!prompt) return null;
      return { id: cid, kind, title: str(raw.title, 200), prompt };
    }
    case 'check': {
      const options = strArr(raw.options, 6, 300);
      if (options.length < 2) return null;
      const answerIndex = clampInt(raw.answerIndex, 0, options.length - 1, 0);
      return {
        id: cid,
        kind,
        title: str(raw.title, 200),
        question: str(raw.question, 1000),
        options,
        answerIndex,
        explanation: str(raw.explanation, 1000),
      };
    }
    case 'flashcard': {
      const front = str(raw.front, 500);
      if (!front) return null;
      return { id: cid, kind, front, back: str(raw.back, 1000) };
    }
    default:
      return null;
  }
}

/**
 * Coerce one raw module, or null if it has no valid cards.
 * @param {object} raw
 * @param {string} [moduleId] stable id (derived from the lesson; child card ids hang off it).
 */
function normalizeModule(raw, moduleId) {
  if (!raw || typeof raw !== 'object') return null;
  const mid = moduleId || rid('m');
  const cards = (Array.isArray(raw.cards) ? raw.cards : [])
    .map((c, ci) => normalizeCard(c, `${mid}-c${ci}`))
    .filter(Boolean);
  if (!cards.length) return null;
  return {
    id: mid,
    title: str(raw.title, 200),
    summary: str(raw.summary, 500),
    cards,
  };
}

/**
 * Coerce raw (model-produced or partial) data into a valid Lesson. Invalid
 * cards/modules are dropped rather than throwing, so a slightly-off model
 * response still yields a usable lesson. Model-supplied identity/provenance is
 * ignored — `meta` (the trusted caller) supplies id, timestamps, and authorModel.
 * @param {object} raw
 * @param {object} [meta] { id, authorModel, createdAt, updatedAt }
 * @returns {Lesson}
 */
function normalizeLesson(raw, meta = {}) {
  const o = raw && typeof raw === 'object' ? raw : {};
  const id = str(meta.id) || rid('lesson');
  const level = LEVELS.includes(str(o.level).toLowerCase()) ? str(o.level).toLowerCase() : 'beginner';
  // Child ids are derived from the lesson id, so they're unique within the lesson
  // and globally unique whenever the lesson id is (see runBuildLesson).
  const modules = (Array.isArray(o.modules) ? o.modules : [])
    .map((m, mi) => normalizeModule(m, `${id}-m${mi}`))
    .filter(Boolean);
  const title = str(o.title, 200) || str(o.topic, 200) || 'Untitled lesson';
  const createdAt = str(meta.createdAt) || null;
  return {
    schemaVersion: SCHEMA_VERSION,
    id,
    slug: slugify(title),
    title,
    subtitle: str(o.subtitle, 300),
    topic: str(o.topic, 500),
    level,
    summary: str(o.summary, 1000),
    objectives: strArr(o.objectives, 10, 300),
    estMinutes: clampInt(o.estMinutes, 1, 600, Math.max(3, cardCount({ modules }) * 2)),
    tags: strArr(o.tags, 12, 40),
    modules,
    sources: (Array.isArray(o.sources) ? o.sources : [])
      .map((s) => ({ title: str(s && s.title, 300), url: str(s && s.url, 1000) }))
      .filter((s) => s.url),
    living: { enabled: !!(o.living && o.living.enabled), lastGrounded: (o.living && str(o.living.lastGrounded)) || null },
    authorModel: str(meta.authorModel) || null,
    createdAt,
    updatedAt: str(meta.updatedAt) || createdAt,
  };
}

// Per-kind shape requirements — what a card of each kind must have to be valid.
// Mirrors what normalizeCard guarantees, but lets validateLesson act as a real
// integrity gate for lessons that did NOT just come through normalizeLesson
// (loaded from disk, hand-edited, migrated from an older schema).
function cardShapeError(c) {
  if (!c || typeof c !== 'object') return 'card is not an object';
  if (!CARD_KINDS.includes(c.kind)) return `unknown card kind "${c && c.kind}"`;
  switch (c.kind) {
    case 'concept': return c.html ? '' : 'concept card missing html';
    case 'media': return c.videoId ? '' : 'media card missing videoId';
    case 'applet': return c.prompt ? '' : 'applet card missing prompt';
    case 'flashcard': return c.front ? '' : 'flashcard missing front';
    case 'check':
      if (!Array.isArray(c.options) || c.options.length < 2) return 'check card needs >=2 options';
      if (!Number.isInteger(c.answerIndex) || c.answerIndex < 0 || c.answerIndex >= c.options.length) return 'check card answerIndex out of range';
      return '';
    default: return `unknown card kind "${c.kind}"`;
  }
}

/**
 * Validate a Lesson's structure AND each card's shape. Returns { ok, errors } —
 * does not throw.
 * @param {Lesson} lesson
 */
function validateLesson(lesson) {
  const errors = [];
  if (!lesson || typeof lesson !== 'object') return { ok: false, errors: ['not an object'] };
  if (lesson.schemaVersion !== SCHEMA_VERSION) errors.push(`schemaVersion must be ${SCHEMA_VERSION}`);
  if (!lesson.title) errors.push('missing title');
  if (!LEVELS.includes(lesson.level)) errors.push('invalid level');
  if (!Array.isArray(lesson.modules) || !lesson.modules.length) errors.push('needs at least one module');
  for (const m of lesson.modules || []) {
    if (!Array.isArray(m.cards) || !m.cards.length) { errors.push(`module "${m && m.title}" has no cards`); continue; }
    for (const c of m.cards) {
      const e = cardShapeError(c);
      if (e) errors.push(e);
    }
  }
  return { ok: errors.length === 0, errors };
}

/** Total number of cards across all modules — the length of the swipe stream. */
function cardCount(lesson) {
  return (lesson.modules || []).reduce((n, m) => n + (m.cards ? m.cards.length : 0), 0);
}

/** Count cards of a given kind across the lesson (used to enforce richness). */
function countKind(lesson, kind) {
  return (lesson.modules || []).reduce((n, m) => n + (m.cards || []).filter((c) => c.kind === kind).length, 0);
}

module.exports = {
  SCHEMA_VERSION,
  LEVELS,
  CARD_KINDS,
  normalizeLesson,
  normalizeModule,
  normalizeCard,
  validateLesson,
  cardShapeError,
  cardCount,
  countKind,
  youtubeId,
  slugify,
};
