'use strict';

// The Lesson artifact — Chervil's portable, interactive learning document.
//
// A Lesson is the keystone primitive for the learning vertical: it is authored
// in the desktop app (generated by Sprig from a topic), rendered as an in-app
// "lesson player", and published to a mobile-friendly, swipeable reader. It
// builds on Chervil's existing primitives — a Lesson is a structured Space of
// composed cards, where interactive cards reuse the applet bridge
// (window.chervil.ask) that composed pages already use.
//
// Design notes live in docs/rfcs/0001-interactive-lessons.md. This module is
// pure data: schema, validation, and normalization of model output. It has no
// I/O and no rendering, so it carries no security surface.

const SCHEMA_VERSION = 1;

const LEVELS = ['beginner', 'intermediate', 'advanced'];

// A lesson is consumed as a flat stream of CARDS grouped into MODULES. The card
// is the unit you swipe through on mobile, so each kind is self-contained.
const CARD_KINDS = ['concept', 'media', 'applet', 'check', 'flashcard'];

/**
 * @typedef {Object} Lesson
 * @property {number} schemaVersion
 * @property {string} id
 * @property {string} slug
 * @property {string} title
 * @property {string} subtitle
 * @property {string} topic              The learner's original ask.
 * @property {'beginner'|'intermediate'|'advanced'} level
 * @property {string} summary            1–2 sentence overview.
 * @property {string[]} objectives       What the learner will be able to do.
 * @property {number} estMinutes
 * @property {string[]} tags
 * @property {Module[]} modules
 * @property {Source[]} sources          Citations from live grounding.
 * @property {{enabled:boolean,lastGrounded:string|null}} living
 * @property {string|null} authorModel   Provenance: provider/model that built it.
 * @property {string|null} createdAt
 * @property {string|null} updatedAt
 *
 * @typedef {Object} Module
 * @property {string} id
 * @property {string} title
 * @property {string} summary
 * @property {Card[]} cards
 *
 * @typedef {Object} Source
 * @property {string} title
 * @property {string} url
 *
 * Card kinds (discriminated by `kind`):
 *   concept   { id, kind, title, html }                         explanatory content (composed HTML; may carry media markers)
 *   media     { id, kind, title, provider:'youtube', videoId, caption, verified }
 *   applet    { id, kind, title, prompt }                       a generative interactive widget; `prompt` tells Sprig what to build (HTML composed at render time)
 *   check     { id, kind, title, question, options[], answerIndex, explanation }
 *   flashcard { id, kind, front, back }
 */

let _seq = 0;
function rid(prefix) {
  // Deterministic-ish local id; not crypto. Avoids Date.now()/Math.random so the
  // module is safe to use in deterministic contexts (and matches repo constraints).
  _seq += 1;
  return `${prefix}_${_seq.toString(36)}`;
}

function str(v, max = 0) {
  let s = v == null ? '' : String(v);
  if (max > 0 && s.length > max) s = s.slice(0, max);
  return s;
}

function strArr(v, maxItems = 0, maxLen = 0) {
  if (!Array.isArray(v)) return [];
  let a = v.map((x) => str(x, maxLen)).filter(Boolean);
  if (maxItems > 0) a = a.slice(0, maxItems);
  return a;
}

function clampInt(v, lo, hi, dflt) {
  const n = Math.round(Number(v));
  if (!Number.isFinite(n)) return dflt;
  return Math.max(lo, Math.min(hi, n));
}

// Extract an 11-char YouTube id from a raw id or any common YouTube URL form.
function youtubeId(raw) {
  const s = str(raw).trim();
  if (/^[a-zA-Z0-9_-]{11}$/.test(s)) return s;
  const m = s.match(/(?:v=|\/embed\/|youtu\.be\/|\/shorts\/)([a-zA-Z0-9_-]{11})/);
  return m ? m[1] : '';
}

function slugify(s) {
  return str(s)
    .toLowerCase()
    .replace(/['"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'lesson';
}

function normalizeCard(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const kind = str(raw.kind).toLowerCase();
  switch (kind) {
    case 'concept':
      return { id: str(raw.id) || rid('c'), kind, title: str(raw.title, 200), html: str(raw.html, 20000) };
    case 'media': {
      const videoId = youtubeId(raw.videoId || raw.url || raw.id);
      if (!videoId) return null; // a media card with no resolvable video is useless
      return {
        id: str(raw.id) || rid('c'),
        kind,
        title: str(raw.title, 200),
        provider: 'youtube',
        videoId,
        caption: str(raw.caption, 500),
        // Model-suggested video ids are NOT trusted until verified (oEmbed/search).
        verified: raw.verified === true,
      };
    }
    case 'applet':
      return { id: str(raw.id) || rid('c'), kind, title: str(raw.title, 200), prompt: str(raw.prompt, 2000) };
    case 'check': {
      const options = strArr(raw.options, 6, 300);
      if (options.length < 2) return null;
      const answerIndex = clampInt(raw.answerIndex, 0, options.length - 1, 0);
      return {
        id: str(raw.id) || rid('c'),
        kind,
        title: str(raw.title, 200),
        question: str(raw.question, 1000),
        options,
        answerIndex,
        explanation: str(raw.explanation, 1000),
      };
    }
    case 'flashcard':
      return { id: str(raw.id) || rid('c'), kind, front: str(raw.front, 500), back: str(raw.back, 1000) };
    default:
      return null;
  }
}

function normalizeModule(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const cards = (Array.isArray(raw.cards) ? raw.cards : []).map(normalizeCard).filter(Boolean);
  if (!cards.length) return null;
  return {
    id: str(raw.id) || rid('m'),
    title: str(raw.title, 200),
    summary: str(raw.summary, 500),
    cards,
  };
}

/**
 * Coerce raw (model-produced or partial) data into a valid Lesson. Invalid
 * cards/modules are dropped rather than throwing, so a slightly-off model
 * response still yields a usable lesson.
 * @param {object} raw
 * @param {object} [meta] { authorModel, createdAt } provenance to stamp.
 * @returns {Lesson}
 */
function normalizeLesson(raw, meta = {}) {
  const o = raw && typeof raw === 'object' ? raw : {};
  const level = LEVELS.includes(str(o.level).toLowerCase()) ? str(o.level).toLowerCase() : 'beginner';
  const modules = (Array.isArray(o.modules) ? o.modules : []).map(normalizeModule).filter(Boolean);
  const title = str(o.title, 200) || str(o.topic, 200) || 'Untitled lesson';
  return {
    schemaVersion: SCHEMA_VERSION,
    id: str(o.id) || rid('lesson'),
    slug: str(o.slug) || slugify(title),
    title,
    subtitle: str(o.subtitle, 300),
    topic: str(o.topic, 500),
    level,
    summary: str(o.summary, 1000),
    objectives: strArr(o.objectives, 10, 300),
    estMinutes: clampInt(o.estMinutes, 1, 600, Math.max(3, modules.reduce((n, m) => n + m.cards.length, 0) * 2)),
    tags: strArr(o.tags, 12, 40),
    modules,
    sources: (Array.isArray(o.sources) ? o.sources : [])
      .map((s) => ({ title: str(s && s.title, 300), url: str(s && s.url, 1000) }))
      .filter((s) => s.url),
    living: { enabled: !!(o.living && o.living.enabled), lastGrounded: (o.living && str(o.living.lastGrounded)) || null },
    authorModel: str(meta.authorModel) || (o.authorModel ? str(o.authorModel) : null),
    createdAt: str(meta.createdAt) || (o.createdAt ? str(o.createdAt) : null),
    updatedAt: str(meta.createdAt) || (o.updatedAt ? str(o.updatedAt) : null),
  };
}

/**
 * Validate a normalized Lesson. Returns { ok, errors } — does not throw.
 * @param {Lesson} lesson
 */
function validateLesson(lesson) {
  const errors = [];
  if (!lesson || typeof lesson !== 'object') return { ok: false, errors: ['not an object'] };
  if (lesson.schemaVersion !== SCHEMA_VERSION) errors.push(`schemaVersion must be ${SCHEMA_VERSION}`);
  if (!lesson.title) errors.push('missing title');
  if (!LEVELS.includes(lesson.level)) errors.push('invalid level');
  if (!Array.isArray(lesson.modules) || !lesson.modules.length) errors.push('needs at least one module');
  let cardCount = 0;
  for (const m of lesson.modules || []) {
    if (!Array.isArray(m.cards) || !m.cards.length) { errors.push(`module "${m.title}" has no cards`); continue; }
    for (const c of m.cards) {
      cardCount += 1;
      if (!CARD_KINDS.includes(c.kind)) errors.push(`unknown card kind "${c.kind}"`);
    }
  }
  if (cardCount === 0) errors.push('lesson has no cards');
  return { ok: errors.length === 0, errors };
}

/** Total number of cards across all modules — the length of the swipe stream. */
function cardCount(lesson) {
  return (lesson.modules || []).reduce((n, m) => n + (m.cards ? m.cards.length : 0), 0);
}

module.exports = {
  SCHEMA_VERSION,
  LEVELS,
  CARD_KINDS,
  normalizeLesson,
  normalizeModule,
  normalizeCard,
  validateLesson,
  cardCount,
  youtubeId,
  slugify,
};
